blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ Questions
    url: https://github.com/vinaysingh282006/History-of-all-flight-crash/discussions
    about: Ask questions or share ideas here.

categories:
  - title: "ğŸ› Bugs"
    label: "bug"
  - title: "ğŸš€ Feature Requests"
    label: "feature-request"
  - title: "âœ¨ Enhancements"
    label: "enhancement"
  - title: "ğŸ”§ Refactoring"
    label: "refactor"
